### PR TITLE
toggle nav manu while not in angular

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
This gets non angular pages to have a working nav while in mobile again.

Issue: https://github.com/mozilla/webmaker.org/issues/1176

**Comment by ScottDowne** [comment]
R? if possible, if not, I can bug others ;)

**Comment by ScottDowne** [comment]
Looks like I broke stuff and didn't notice.

**Comment by k88hudson** [comment]
@ScottDowne do you need to fix before I review then?

**Comment by ScottDowne** [comment]
Yeah, found another bug in it too. my height was also off by a few pixels.

**Comment by ScottDowne** [comment]
Fixed!

**Comment by k88hudson** [comment]
I can't logout on non-angular pages

**Comment by ScottDowne** [comment]
Good catch, updated.

**Comment by k88hudson** [comment]
Ok looks good to me R+

**Pull request merged**
