### PR TITLE
T1178

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes: #1178
link directive and copy fixes for Make Your Own pages

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos, @gesa, @k88hudson can you look at what I did to the `link` directive? It's very strange that it requires me to `$observe` it. Feels like a hack. Not even `$timeout` works properly. Weird loading order or something?

@alicoding Why was the `/madewithcode-meme` page complaining about a missing i18n string, "Made with Code"? Once I added it, the runtime error in console went away, but `grunt validate` would fail. In the end, I had to add it to `ignoreKeys`, but ... something feels wrong.

**Comment by alicoding** [comment]
@secretrobotron that's because the string 'Made with Code' is not in the template directly, but it is in the JS file which we are not including that. So, I think this is intentional and normal.

**Comment by secretrobotron** [comment]
Got it. Thanks @alicoding. For future reference: https://github.com/mozilla/webmaker.org/blob/master/public/js/angular/app.js#L53

**Comment by secretrobotron** [comment]
R+ from @k88hudson

**Pull request merged**
