### PR TITLE
Fixes #1407 - redirect a fews page to Teach site

### LINKED ISSUE #1407: Redirect a few pages to the Teach site
Let's make a list of urls that need to be redirected once the new site is live:
 * [ ] `webmaker.org/resources` should go to `teach.mozilla.org/teach-like-mozilla/web-literacy/`
 * [ ] `webmaker.org/literacy` should go to `teach.mozilla.org/teach-like-mozilla/web-literacy/`
 * [ ] `webmaker.org/party` should go to `teach.mozilla.org/events`
 * [ ] `party.webmaker.org` should go to `teach.mozilla.org/events`
  - I believe the Maker Party site is a separate app.  Might need @jbuck 's help killing it + redirect?
 * [ ] `https://webmaker.org/mentor` should go to `teach.mozilla.org`

(Original ticket on Teach site repo: https://github.com/mozilla/teach.webmaker.org/issues/266)

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #1407 

 * [x] `webmaker.org/resources` should go to `teach.mozilla.org/teach-like-mozilla/web-literacy/`
 * [x] `webmaker.org/literacy` should go to `teach.mozilla.org/teach-like-mozilla/web-literacy/`
 * [x] `webmaker.org/party` should go to `teach.mozilla.org/events`
 * [x] `https://webmaker.org/mentor` should go to `teach.mozilla.org`

### CODE REVIEW

**Comment by thisandagain** [comment]
Simple enough! Looks good but the PR is failing the tests for changes to the `redirect.js` file.

**Comment by mmmavis** [comment]
heh, this is what happened when I got lazy and didn't want to wait for Travis to finish :)

@thisandagain review again?

**Comment by thisandagain** [comment]
Looks great. R+

**Comment by mmmavis** [comment]
Thanks @thisandagain !  I'm gonna wait till next Monday to merge and push :bowtie:

**Pull request merged**
