### PR TITLE
Clean up EOY campaign in webmaker.org

### PR DESCRIPTION
**Pull request by alicoding**
This patch basically remove an unused code from 2013 EOY campaign. To test this patch you can simple run `node app.js` and just have to make sure nothing crash or wrong especially when you have `FLAGS_CAMPAIGN` set to any number that is positive (not `0`).

### CODE REVIEW

**Comment by alicoding** [comment]
@simonwex what is the best way or process of getting someone to review a patch here on github?

**Comment by simonwex** [comment]
@alicoding find a reviewer by asking mofo-eng@mozillafoundation.org or on irc in #webmaker and then assign it to them.

**Comment by simonwex** [comment]
Oh, and including instructions to test in the description above helps a lot. If you do that, I'm happy to review.

**Comment by ScottDowne** [comment]
I think you need to remove this stuff too: https://github.com/mozilla/webmaker.org/search?utf8=%E2%9C%93&q=campaign-header

**Comment by alicoding** [comment]
@ScottDowne this is now fixed. Can you re-review? Thanks!

**Comment by ScottDowne** [comment]
This was an in person r+

**Pull request merged**
