### PR TITLE
verify login for badge detail page

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
Not sure if I'm using verify the way it's intended to be used.

The reason I need this is because login events have already been fired by the time this page gets around to loading.

**Comment by jbuck** [comment]
Hm, I don't know if you want to call verify() here... can you query the current login status somehow?

**Comment by ScottDowne** [comment]
What is the purpose of verify if not to verify the login?

I'll take a look though.

**Comment by ScottDowne** [comment]
I wonder if we could just fire any newly added onloging events added if login has already happened?

But I'm not seeing anything helpful on auth or auth.wmLogin for the status.

**Comment by jbuck** [comment]
@ScottDowne r+

**Pull request merged**
