### PR TITLE
Update favicon. Resolves GH-1416

### PR DESCRIPTION
**Pull request by thisandagain**
Resolves critical issue GH-1416

### CODE REVIEW

**Comment by thisandagain** [comment]
@secretrobotron R?

**Comment by cassiemc** [comment]
Can we close this @secretrobotron ?

**Comment by cassiemc** [comment]
@secretrobotron @xmatthewx I'm not sure what this bug covered but for legal reasons as per https://bugzilla.mozilla.org/show_bug.cgi?id=1159016 we do need to ensure that the old webmaker favicon is updated.

**Comment by secretrobotron** [comment]
@cassiemc can you list concerns you have in https://github.com/MozillaFoundation/plan/issues/480?
This bug and this logo are sooo out of date.

**Comment by cassiemc** [comment]
@secretrobotron sounds good! Can you close this? I don't have an option to...

**Comment by secretrobotron** [comment]
@cassiemc it's not actually an open bug. It's a pull request that was merged a while ago (so, it's effectively closed). How did you find it?

**Comment by cassiemc** [comment]
Ah I see! It was linked to in that bugzilla issue which I keep getting notifications from.

**Pull request merged**
