### PR TITLE
Private eye footer for MozillaFoundation/plan#196

### PR DESCRIPTION
**Pull request by gesa**

### CODE REVIEW

**Comment by gesa** [comment]
@iamjessklein Screenshots for you! :smile:

**Comment by davidascher** [comment]
The mozilla wordmark looks aliased in at least two of those screenshots @gesa, wouldn't you say?

**Comment by gesa** [comment]
@davidascher I think that's just the screenshots. it looks right in my browsers. (also unchanged in this PR)

**Comment by thisandagain** [comment]
@gesa @davidascher Confirmed ok on the aliasing locally. R+

**Pull request merged**
