### PR TITLE
sms/twilio design fixes

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes https://github.com/mozilla/webmaker.org/issues/1321

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos @iamjessklein R?

**Comment by cadecairos** [comment]
dropdown

can/should we fix up that dropdown's width?

**Comment by secretrobotron** [comment]
oh, totes.

**Comment by secretrobotron** [comment]
@cadecairos @iamjessklein r?

**Comment by secretrobotron** [comment]
@cadecairos actually, had to remove the full-width country code dropdown. html is pretty difficult to deal with there.

**Comment by cadecairos** [comment]
R+

**Pull request merged**
