### PR TITLE
updates to claim code UI

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by k88hudson** [comment]
I would make that claim code button an actual `btn btn-default`. It's a bit too hidden to just show it on hover i think.

**Comment by k88hudson** [comment]
Also, it's a bit weird if you have the application open and then open the claim code, closing one will also close the other

**Comment by k88hudson** [comment]
Mostly looks good though :)

**Comment by ScottDowne** [comment]
We wanted the claim code button to be less prominent than the apply button.

Initially was going to be a link.

**Comment by ScottDowne** [comment]
I'll sort out the application-on thing a bit. It's a bit weird now.

**Comment by k88hudson** [comment]
@ScottDowne this looks fine to me. R+

**Pull request merged**
