### PR TITLE
upgrade font awesome

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
R?

**Comment by k88hudson** [comment]
Just a few little nits:

* on `/explore`, heart is misaligned: , also on `/search` 

* on badge pages, checkmark is misaligned: image (should be centered)
* on `/localweb`, the video play icon is tiny 
image

**Comment by ScottDowne** [comment]
Updated

**Comment by k88hudson** [comment]
@ScottDowne :dancer: looks good!

**Pull request merged**
