### PR TITLE
Use new standard privacy policy. Resolves GH-1402

### PR DESCRIPTION
**Pull request by thisandagain**

### CODE REVIEW

**Comment by thisandagain** [comment]
@secretrobotron R?

**Comment by secretrobotron** [comment]
The link on `/` didn't change. Matter?

**Comment by secretrobotron** [comment]
Same for `/explore`, etc. Doesn't matter if we're going to change up the site a whole bunch. But, feels like there's another template you missed.

**Comment by thisandagain** [comment]
Good catch... looks like we have this defined in a bunch of different / ways places. Will update.

**Comment by thisandagain** [comment]
@secretrobotron Re-R?

**Comment by secretrobotron** [comment]
Btw, the same url needs to be changed in login now too.

**Comment by secretrobotron** [comment]
R+, but just check out https://github.com/mozilla/webmaker.org/pull/1406#issuecomment-102152816.

**Comment by thisandagain** [comment]
Follow-up for id.webmaker.org filed here: https://github.com/mozilla/id.webmaker.org/issues/295

**Pull request merged**
