### PR TITLE
T1299

### LINKED ISSUE #1299: US Phone number is problematic
*OS:* OSX
*Browser:* Chrome 40.0.2214.111 (64-bit)
*Screenshot:* https://www.dropbox.com/s/ilpig5dkx04aelb/Screenshot%202015-02-24%2010.17.47.png?dl=0

**Repro Steps:**
1. Choose US
2. Enter 2061231234

**Expected:** "Send Text" button should be enabled
**Actual:** "Send Text" button is disabled

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes #1299

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos r?

**Comment by secretrobotron** [comment]
@gavinsharp r?

**Comment by cadecairos** [comment]
@gvn

**Comment by cadecairos** [comment]
a few things to clean up:

1. The error message is visible when the form is first displayed.
2. The message should probably not appear if the input is blurred, but empty
3. When I blur the input I see the message twice?

**Comment by secretrobotron** [comment]
@cadecairos should be fine now.

**Comment by cadecairos** [comment]
r+

**Pull request merged**
