### PR TITLE
Tweaks - disabled India Report link, replaced video with the real one

### PR DESCRIPTION
**Pull request by mmmavis**

### CODE REVIEW

**Comment by edrushka** [comment]
@simonwex pinging so this doesn't fall through the cracks. I know there's a ton happening today. Thanks.

**Comment by mmmavis** [comment]
updates: we are having problem with video link, will replace it with a new one soon.  do NOT merge this PR yet

**Comment by simonwex** [comment]
@mmmavis let me know when you want a review, it looks good once linting passes.

**Comment by mmmavis** [comment]
@simonwex 
Video link has been updated again! Review :+1: ?

**Comment by thisandagain** [comment]
Thanks for getting the india link updated @mmmavis !

**Comment by simonwex** [comment]
R+ :+1:

**Comment by edrushka** [comment]
I can't see these changes live, even with command-R. When will they be visible?

**Comment by HPaulJohnson** [comment]
Blog post and press event tomorrow (3/1) afternoon (Barcelona time) so let's make sure all changes go live today. Thx!

**Comment by mmmavis** [comment]
@simonwex I can help with deploying but I'm not sure if the `master` branch contains anything that shouldn't be pushed to prod :open_mouth: 

cc @secretrobotron @jbuck

**Comment by jdotpz** [comment]
We're doing press on it for a Sunday, and this is the first we're hearing about it in DevOps going live over the weekend?  For shame!  :)

I'll look at the branch Mavis

**Comment by jdotpz** [comment]
https://github.com/mozilla/webmaker.org/compare/5ce88bf...abd738b is the compare between the last tag that went to prod (v1.1.139) and the newer branch.  @k88hudson and @secretrobotron have some lint / styling updates that didn't go with any tag yet, but that shouldn't block us to push this to staging mavis.  Go ahead and do the tagging process we worked on.

*git checkout master*
*git pull*
*npm version patch*
*git push mozilla master --tags* (I think this is right, you can verify in your history mavis)

That will auto build and push to staging.  Verify your changes there, and then you can use Jenkins to go to prod!

**Comment by k88hudson** [comment]
@mmmavis go for it, everything is good to push

**Comment by k88hudson** [comment]
also, that's correct jp

**Comment by edrushka** [comment]
Update: @mmmavis will do this around 11pm Pacific tonight (Saturday March 28).

**Comment by mmmavis** [comment]
v1.1.140 on [staging](https://webmaker.mofostaging.net/localweb) Everything looks fine.  I'm gonna push it to prod now.

**Comment by mmmavis** [comment]
v1.1.140 on prod now.

**Pull request merged**
