### PR TITLE
Redirect me page

### PR DESCRIPTION
**Pull request by cadecairos**
MozillaFoundation/plan#569

Blocked by mozilla/teach.mozilla.org#1276

### CODE REVIEW

**Comment by jbuck** [comment]
I don't think we need to do this patch because we're deprecating this version of webmaker.org entirely. We'll need to add a /me redirect to https://github.com/mozilla/webmaker-browser though

**Comment by cadecairos** [comment]
so, webmaker.org/me will redirect nowhere?

**Comment by jbuck** [comment]
Not quite - Take a look at the plan again for beta.webmaker.org:

7. beta.webmaker.org
  - [ ] [Add redirect](https://github.com/mozilla/webmaker.org/pull/1434) from `/me` to `teach.mozilla.org/me`
  - [ ] Change webmaker.org to point at beta.webmaker.org. Keep beta.webmaker.org DNS around since it's been used for awhile.
  - [ ] Add redirect for beta.webmaker.org to webmaker.org

**Comment by cadecairos** [comment]
how will a person know to go from `beta.webmaker.org` to `beta.webmaker.org/me`?

**Pull request closed without merging**
