### PR TITLE
Create new, simplified gallery route for /explore

### PR DESCRIPTION
**Pull request by cadecairos**
#1177

### CODE REVIEW

**Comment by alicoding** [comment]
r+

**Comment by alicoding** [comment]
Why this is branch on `upstream`/`mozilla` remote? LOL

**Comment by cadecairos** [comment]
must have misconfigured my remotes

**Comment by cadecairos** [comment]
moved to #1211

**Comment by cadecairos** [comment]
Having trouble deploying to staging: https://jenkins.mofoprod.net/job/webmakerorg/315/console

**Pull request closed without merging**
