### PR TITLE
Added gifs and phone containers.

### LINKED ISSUE #1294: Phones are empty
*OS:* OSX
*Browser:* Chrome 40.0.2214.111 (64-bit)
*Screenshot:* https://www.dropbox.com/s/9dgjaotu8cb4a99/Screenshot%202015-02-24%2010.09.12.png?dl=0

**Repro Steps:**
1. Load page https://webmaker.mofostaging.net/app

**Expected:** See contents in phone wrapper per design
**Actual:** See screenshot

### LINKED ISSUE #1298: Install Page - Devices / GIFs are not center aligned
They are all shifted to the right on FFOS:

screen shot 2015-02-24 at 12 53 07 pm

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes #1298
fixes #1294

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos @k88hudson r?

**Comment by cadecairos** [comment]
lgtm! :+1:

**Comment by cadecairos** [comment]
width-app-install

at 320x480

**Comment by secretrobotron** [comment]
@k88hudson is fixing the responsive design problem separately.

**Pull request merged**
