### PR TITLE
Better background for onboarding screen

### LINKED ISSUE #1115: Tweak background darkness & saturation
I think the green background could be tweaked slightly for better readability of the yellow type, and a slightly richer, more inviting green.

Here's one to try – though @xmatthewx may want to alter the original for better quality.

bkg-green

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes #1115

### CODE REVIEW

**Comment by secretrobotron** [comment]
1. Included size-reduced green background jpg for onboarding splash.
2. Replaced corresponding png with a jpg.
3. Fixed css appropriately.

**Comment by secretrobotron** [comment]
@ScottDowne R?

**Comment by ScottDowne** [comment]
Looks like there is an updated non retina version in #1115 now too.

**Comment by secretrobotron** [comment]
Thanks @ScottDowne !

**Comment by ScottDowne** [comment]
R+ once travis is done and it's green.

**Pull request merged**
